package com.mdgenerator.server.database;

import java.util.Arrays;
import java.util.List;

import com.mdgenerator.server.common.DbTableInfo;
import com.mdgenerator.server.common.DbTableInfo.DbColumnInfo;
import com.mdgenerator.server.core.MdBuilder;
import com.mdgenerator.server.core.MdDocument;

/**
 * 数据库表结构→Markdown文档生成器
 * 
 * <p>将DbReader读取的表结构信息转换为格式化的Markdown文档。
 * 生成的文档包含每张表的详细信息：表名、注释、引擎、字段列表等。</p>
 * 
 * <p>文档结构：</p>
 * <pre>
 * # 数据库设计文档
 * > 数据库: mydb | 生成时间: 2024-05-21
 * 
 * ## 1. user_info (用户信息表)
 * | 序号 | 字段名 | 类型 | 主键 | 非空 | 默认值 | 说明 |
 * | ... | ... | ... | ... | ... | ... | ... |
 * </pre>
 * 
 * <p>所有生成的表格采用左对齐格式，字段按在表中的顺序排列。
 * 主键字段会用PK标记，自增字段会用自增标记。</p>
 * 
 * @author MD Generator Team
 * @version 1.0.0
 */
public class DbDocGenerator {

    /** Markdown构建器，用于链式构建文档内容 */
    private MdBuilder mdBuilder;

    /**
     * 默认构造函数
     * 
     * <p>初始化内部MdBuilder实例，为后续的文档构建做准备</p>
     */
    public DbDocGenerator() {
        this.mdBuilder = new MdBuilder();
    }

    private boolean isZh = true;

    private String zh(String zh, String en) { return isZh ? zh : en; }

    /**
     * 将数据库表结构信息生成完整的Markdown文档
     */
    public MdDocument generate(List<DbTableInfo> tables, String databaseName, String dbType) {
        mdBuilder.reset();
        String ttl = zh("数据库设计文档", "Database Design Document");
        mdBuilder.addH1(ttl);

        String meta = "**" + zh("数据库", "Database") + "**: " + databaseName
                + " | **" + zh("类型", "Type") + "**: " + dbType.toUpperCase()
                + " | **" + zh("表数量", "Tables") + "**: " + tables.size()
                + " | **" + zh("生成时间", "Generated") + "**: "
                + new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date());
        mdBuilder.addParagraph(meta);
        mdBuilder.addHorizontalRule();

        generateTableOfContents(tables);
        mdBuilder.addHorizontalRule();

        for (int i = 0; i < tables.size(); i++) {
            generateSingleTable(tables.get(i), i + 1);
        }

        mdBuilder.addHorizontalRule();
        mdBuilder.addParagraph("*" + zh("本文档由 MD Generator 自动生成", "Generated by MD Generator") + "*");
        return new MdDocument(ttl + " - " + databaseName, mdBuilder.build()).setVersion("1.0.0");
    }

    /**
     * 设置语言: "zh" 中文, "en" 英文
     */
    public DbDocGenerator setLanguage(String lang) {
        this.isZh = !"en".equalsIgnoreCase(lang);
        return this;
    }

    private void generateTableOfContents(List<DbTableInfo> tables) {
        mdBuilder.addH2(zh("目录", "Index"));
        for (int i = 0; i < tables.size(); i++) {
            DbTableInfo t = tables.get(i);
            String dn = t.getDisplayName();
            String anchor = t.getTableName().toLowerCase().replaceAll("[^a-z0-9]", "-");
            mdBuilder.appendRaw("- [" + (i + 1) + ". " + dn + "](#" + anchor + ")\n");
        }
        mdBuilder.appendRaw("\n");
    }

    private void generateSingleTable(DbTableInfo table, int index) {
        String anchor = table.getTableName().toLowerCase().replaceAll("[^a-z0-9]", "-");
        mdBuilder.appendRaw("<a id=\"" + anchor + "\"></a>\n");

        if (table.getTableComment() != null && !table.getTableComment().isEmpty()
                && !table.getTableComment().equals(table.getTableName())) {
            mdBuilder.addH2(index + ". " + table.getTableName() + " (" + table.getTableComment() + ")");
        } else {
            mdBuilder.addH2(index + ". " + table.getTableName());
        }

        StringBuilder bi = new StringBuilder();
        if (table.getEngine() != null && !table.getEngine().isEmpty())
            bi.append("**" + zh("存储引擎", "Engine") + "**: ").append(table.getEngine()).append(" | ");
        if (table.getCharset() != null && !table.getCharset().isEmpty())
            bi.append("**" + zh("字符集", "Charset") + "**: ").append(table.getCharset()).append(" | ");
        bi.append("**" + zh("字段数", "Columns") + "**: ").append(table.getColumnCount());
        mdBuilder.addParagraph(bi.toString());

        generateColumnTable(table.getColumns());
        mdBuilder.addHorizontalRule();
    }

    private void generateColumnTable(List<DbColumnInfo> columns) {
        List<String> headers = Arrays.asList(
            zh("序号", "#"), zh("字段名", "Name"), zh("类型", "Type"),
            zh("主键", "PK"), zh("非空", "NotNull"), zh("默认值", "Default"), zh("说明", "Description")
        );
        java.util.List<java.util.List<String>> rows = new java.util.ArrayList<>();
        for (int i = 0; i < columns.size(); i++) {
            DbColumnInfo col = columns.get(i);
            StringBuilder cmt = new StringBuilder();
            if (col.getColumnComment() != null && !col.getColumnComment().isEmpty()) cmt.append(col.getColumnComment());
            if (col.isAutoIncrement()) {
                String ai = zh("自增", "AutoInc");
                cmt.append(cmt.length() > 0 ? "，" + ai : ai);
            }
            rows.add(Arrays.asList(
                String.valueOf(i + 1), col.getColumnName(), col.getColumnType(),
                col.isPrimaryKey() ? "✓" : "",
                "NO".equals(col.getIsNullable()) ? "✓" : "",
                col.getDefaultValue() != null ? col.getDefaultValue() : "",
                cmt.toString()
            ));
        }
        mdBuilder.addTable(headers, rows);
    }
}