package com.mdgenerator.server.apidoc;

import java.text.SimpleDateFormat;
import java.util.*;

import com.mdgenerator.server.apidoc.ApiInfo.ApiParam;
import com.mdgenerator.server.core.MdBuilder;
import com.mdgenerator.server.core.MdDocument;

/**
 * API接口文档→Markdown生成器
 * 
 * <p>将ControllerParser解析出的API信息列表转换为格式化的Markdown接口文档。
 * 生成的文档按Controller分组展示，每个接口显示其路径、HTTP方法、参数和返回值。</p>
 * 
 * <p>文档结构示例：</p>
 * <pre>
 * # API接口文档
 * 
 * ## UserController（用户管理）
 * 
 * ### 1. POST /api/user （创建用户）
 * **请求参数：**
 * | 参数名 | 类型 | 必填 | 位置 | 说明 |
 * | ... | ... | ... | ... | ... |
 * 
 * **返回类型：** Result
 * </pre>
 * 
 * <p>设计要点：</p>
 * <ul>
 *   <li>同一组的接口共享一个章节（按Controller分组）</li>
 *   <li>每个接口独立显示，标注HTTP方法和完整路径</li>
 *   <li>参数按类型（path/query/body/header）分别展示</li>
 *   <li>使用Badge标记废弃接口</li>
 * </ul>
 * 
 * @author MD Generator Team
 * @version 1.0.0
 */
public class ApiDocGenerator {

    /** Markdown构建器，用于链式构建文档内容 */
    private MdBuilder mdBuilder;
    private boolean isZh = true;

    private String zh(String zh, String en) { return isZh ? zh : en; }

    public ApiDocGenerator setLanguage(String lang) {
        this.isZh = !"en".equalsIgnoreCase(lang);
        return this;
    }

    /**
     * 默认构造函数，初始化内部MdBuilder实例
     */
    public ApiDocGenerator() { this.mdBuilder = new MdBuilder(); }

    public MdDocument generate(Map<String, List<ApiInfo>> controllerApis, String title) {
        mdBuilder.reset();
        mdBuilder.addH1(title != null ? title : zh("API接口文档", "API Documentation"));

        int totalApis = controllerApis.values().stream().mapToInt(List::size).sum();
        String meta = "**" + zh("Controller数量", "Controllers") + "**: " + controllerApis.size()
                + " | **" + zh("接口总数", "Total APIs") + "**: " + totalApis
                + " | **" + zh("生成时间", "Generated") + "**: " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
        mdBuilder.addParagraph(meta);
        mdBuilder.addHorizontalRule();

        generateTableOfContents(controllerApis);
        mdBuilder.addHorizontalRule();

        // 遍历每个Controller，生成接口文档
        int apiIndex = 1;
        for (Map.Entry<String, List<ApiInfo>> entry : controllerApis.entrySet()) {
            String controllerName = entry.getKey();
            List<ApiInfo> apis = entry.getValue();

            // Controller章节标题
            String tag = apis.isEmpty() ? "" : (apis.get(0).getTag() != null ? apis.get(0).getTag() : "");
            String heading = controllerName;
            if (!tag.isEmpty() && !tag.equals(controllerName)) {
                heading = controllerName + "（" + tag + "）";
            }
            mdBuilder.addH2(heading);

            // 生成该Controller下的所有接口
            for (ApiInfo api : apis) {
                generateSingleApi(api, apiIndex++);
            }

            mdBuilder.addHorizontalRule();
        }

        // 页脚
        mdBuilder.addParagraph("*" + zh("本文档由 MD Generator 自动生成", "Generated by MD Generator") + "*");

        return new MdDocument(title, mdBuilder.build()).setVersion("1.0.0");
    }

    /**
     * 生成文档目录（Table of Contents）
     * 
     * <p>目录按Controller分组，每组列出其下的接口路径</p>
     * 
     * @param controllerApis 按Controller分组的API信息
     */
    private void generateTableOfContents(Map<String, List<ApiInfo>> controllerApis) {
        mdBuilder.addH2("目录");

        for (Map.Entry<String, List<ApiInfo>> entry : controllerApis.entrySet()) {
            String controllerName = entry.getKey();
            List<ApiInfo> apis = entry.getValue();

            // 生成Controller的锚点链接
            String controllerAnchor = controllerName.toLowerCase().replaceAll("[^a-z0-9\\u4e00-\\u9fa5]", "-");
            mdBuilder.appendRaw("- [" + controllerName + "](#" + controllerAnchor + ")\n");

            // 生成该Controller下每个接口的子项
            for (ApiInfo api : apis) {
                String method = api.getHttpMethod();
                String path = api.getPath();
                String summary = api.getSummary();
                mdBuilder.appendRaw("  - [" + method + " " + path + "](#" + method.toLowerCase() + "-" + path.replace("/", "").replace("{", "").replace("}", "") + ")\n");
            }
        }
        mdBuilder.appendRaw("\n");
    }

    /**
     * 生成单个API接口的Markdown文档
     * 
     * <p>生成的文档包含：</p>
     * <ol>
     *   <li>接口标题（HTTP方法 + 路径 + 描述）</li>
     *   <li>请求参数表格（如有）</li>
     *   <li>返回值说明</li>
     *   <li>代码示例（curl命令）</li>
     * </ol>
     * 
     * @param api API接口信息
     * @param index 接口序号（全局序号）
     */
    private void generateSingleApi(ApiInfo api, int index) {
        // 接口标题
        StringBuilder title = new StringBuilder();
        title.append(index).append(". ");
        if (api.isDeprecated()) {
            title.append("~~"); // 已废弃接口使用删除线标记
        }
        title.append(api.getHttpMethod()).append(" ").append(api.getPath());
        if (api.getSummary() != null && !api.getSummary().isEmpty()) {
            title.append(" （").append(api.getSummary()).append("）");
        }
        if (api.isDeprecated()) {
            title.append("~~ [已废弃]");
        }
        mdBuilder.addH3(title.toString());

        // 接口基本信息
        StringBuilder basicInfo = new StringBuilder();
        basicInfo.append("**Controller**: `").append(api.getControllerClass()).append("` | ");
        basicInfo.append("**Method**: `").append(api.getMethodName()).append("()`");
        mdBuilder.addParagraph(basicInfo.toString());

        // 请求参数表格（分类型展示）
        List<ApiParam> queryParams = new ArrayList<>();
        List<ApiParam> pathParams = new ArrayList<>();
        List<ApiParam> bodyParams = new ArrayList<>();
        List<ApiParam> headerParams = new ArrayList<>();

        // 按参数类型分组
        for (ApiParam param : api.getParameters()) {
            switch (param.getParamType()) {
                case "path":
                    pathParams.add(param);
                    break;
                case "query":
                    queryParams.add(param);
                    break;
                case "body":
                    bodyParams.add(param);
                    break;
                case "header":
                    headerParams.add(param);
                    break;
                default:
                    queryParams.add(param);
                    break;
            }
        }

        // 生成路径参数表格
        if (!pathParams.isEmpty()) {
            generateParamTable(pathParams, zh("路径参数", "Path Params"));
        }
        if (!queryParams.isEmpty()) {
            generateParamTable(queryParams, zh("Query参数", "Query Params"));
        }
        if (!bodyParams.isEmpty()) {
            generateParamTable(bodyParams, zh("请求体参数", "Body Params"));
        }
        if (!headerParams.isEmpty()) {
            generateParamTable(headerParams, zh("请求头参数", "Header Params"));
        }

        // 生成返回值说明
        generateReturnInfo(api);

        // 生成示例curl命令（方便开发者快速测试）
        generateCurlExample(api);

        mdBuilder.addEmptyLine();
    }

    /**
     * 生成参数详细信息的Markdown表格
     * 
     * <p>表格包含5列：参数名、类型、必填、位置、说明。</p>
     * 
     * @param params 参数列表
     * @param tableTitle 表格标题
     */
    private void generateParamTable(List<ApiParam> params, String tableTitle) {
        mdBuilder.addH4(tableTitle);

        // 定义表头（5列格式）
        List<String> headers = Arrays.asList(
            zh("参数名", "Name"), zh("类型", "Type"), zh("必填", "Required"),
            zh("默认值", "Default"), zh("说明", "Description")
        );

        // 构建数据行
        List<List<String>> rows = new ArrayList<>();
        for (ApiParam param : params) {
            rows.add(Arrays.asList(
                param.getName(),                              // 参数名
                param.getDataType(),                          // 数据类型
                param.isRequired() ? zh("是", "Yes") : zh("否", "No"),            // 是否必填
                param.getDefaultValue() != null ? param.getDefaultValue() : "-",  // 默认值
                param.getDescription() != null ? param.getDescription() : "-"     // 说明
            ));
        }

        mdBuilder.addTable(headers, rows);
    }

    /**
     * 生成返回值说明部分
     * 
     * @param api API接口信息
     */
    private void generateReturnInfo(ApiInfo api) {
        mdBuilder.addH4(zh("返回值", "Return Type"));
        StringBuilder returnInfo = new StringBuilder();
        returnInfo.append("**" + zh("返回类型", "Type") + "**: `").append(api.getReturnType()).append("`");

        if (api.getReturnDescription() != null && !api.getReturnDescription().isEmpty()) {
            returnInfo.append("\n\n").append(api.getReturnDescription());
        }

        mdBuilder.addParagraph(returnInfo.toString());
    }

    /**
     * 生成curl命令示例
     * 
     * <p>根据接口的HTTP方法和参数自动生成curl测试命令。
     * 这可以帮助开发者快速验证接口功能。</p>
     * 
     * <p>生成的curl命令包含：</p>
     * <ul>
     *   <li>HTTP方法（-X GET/POST/PUT/DELETE）</li>
     *   <li>请求头（如Content-Type: application/json）</li>
     *   <li>完整URL（包含路径参数和查询参数）</li>
     *   <li>请求体（POST/PUT方法，JSON格式）</li>
     * </ul>
     * 
     * @param api API接口信息
     */
    private void generateCurlExample(ApiInfo api) {
        StringBuilder curl = new StringBuilder();
        String method = api.getHttpMethod();

        // 构建curl命令
        curl.append("# " + zh("请求示例", "Example") + "\n");
        curl.append("```bash\n");

        // 处理POST/PUT/PATCH等需要请求体的方法
        if ("POST".equals(method) || "PUT".equals(method) || "PATCH".equals(method)) {
            curl.append("curl -X ").append(method).append(" \\\n");
            curl.append("  http://localhost:8080").append(formatPathWithParams(api.getPath())).append(" \\\n");
            curl.append("  -H \"Content-Type: application/json\" \\\n");

            // 如果有body参数，构建JSON示例
            if (!api.getParameters().isEmpty()) {
                StringBuilder jsonBody = new StringBuilder("{\n");
                for (ApiParam param : api.getParameters()) {
                    if ("body".equals(param.getParamType())) {
                        jsonBody.append("    \"").append(param.getName()).append("\": \"\",\n");
                    }
                }
                jsonBody.append("  }");
                curl.append("  -d '").append(jsonBody.toString()).append("'");
            }
        } else {
            // GET/DELETE等方法的curl命令
            curl.append("curl -X ").append(method).append(" \\\n");
            curl.append("  http://localhost:8080").append(formatPathWithParams(api.getPath()));
        }

        curl.append("\n```");
        mdBuilder.appendRaw(curl.toString());
    }

    /**
     * 格式化路径，将路径参数替换为示例值
     * 
     * <p>例如：/user/{id} → /user/1</p>
     * 
     * @param path 原始路径
     * @return 替换路径参数后的示例路径
     */
    private String formatPathWithParams(String path) {
        // 将{paramName}替换为示例值（使用1作为示例）
        return path.replaceAll("\\{[^}]+\\}", "1");
    }

    /**
     * 将API列表分组（按第一个path段分组）
     * 
     * <p>这是一个常用的工具方法，可以替代按Controller分组的方式。
     * 当没有Controller信息（如从Swagger JSON导入）时使用此方法。</p>
     * 
     * @param apis API信息列表
     * @return 按分组名分组的API Map
     */
    public static Map<String, List<ApiInfo>> groupByPathPrefix(List<ApiInfo> apis) {
        Map<String, List<ApiInfo>> grouped = new LinkedHashMap<>();
        for (ApiInfo api : apis) {
            String path = api.getPath();
            // 取第一个/后的第一段作为分组名
            String group = path;
            if (path.startsWith("/")) {
                int nextSlash = path.indexOf("/", 1);
                if (nextSlash > 0) {
                    group = path.substring(1, nextSlash);
                } else {
                    group = path.substring(1);
                }
            }
            grouped.computeIfAbsent(group, k -> new ArrayList<>()).add(api);
        }
        return grouped;
    }
}